export const CREATE_BUSINESS_REQUEST = "CREATE_BUSINESS_REQUEST";
export const CREATE_BUSINESS_SUCCESS = "CREATE_BUSINESS_SUCCESS";
export const CREATE_BUSINESS_FAILURE = "CREATE_BUSINESS_FAILURE";

export const UPDATE_BUSINESS_REQUEST = "UPDATE_BUSINESS_REQUEST";
export const UPDATE_BUSINESS_SUCCESS = "UPDATE_BUSINESS_SUCCESS";
export const UPDATE_BUSINESS_FAILURE = "UPDATE_BUSINESS_FAILURE";

export const FETCH_BUSINESSS_REQUEST = "FETCH_BUSINESSS_REQUEST";
export const FETCH_BUSINESSS_SUCCESS = "FETCH_BUSINESSS_SUCCESS";
export const FETCH_BUSINESSS_FAILURE = "FETCH_BUSINESSS_FAILURE";

export const FETCH_BUSINESS_BY_ID_REQUEST = "FETCH_BUSINESS_BY_ID_REQUEST";
export const FETCH_BUSINESS_BY_ID_SUCCESS = "FETCH_BUSINESS_BY_ID_SUCCESS";
export const FETCH_BUSINESS_BY_ID_FAILURE = "FETCH_BUSINESS_BY_ID_FAILURE";

export const FETCH_BUSINESS_BY_OWNER_REQUEST = "FETCH_BUSINESS_BY_OWNER_REQUEST";
export const FETCH_BUSINESS_BY_OWNER_SUCCESS = "FETCH_BUSINESS_BY_OWNER_SUCCESS";
export const FETCH_BUSINESS_BY_OWNER_FAILURE = "FETCH_BUSINESS_BY_OWNER_FAILURE";

export const SEARCH_BUSINESSS_REQUEST = "SEARCH_BUSINESSS_REQUEST";
export const SEARCH_BUSINESSS_SUCCESS = "SEARCH_BUSINESSS_SUCCESS";
export const SEARCH_BUSINESSS_FAILURE = "SEARCH_BUSINESSS_FAILURE";
