server:
  port: 5003

spring:
  application:
    name: booking

  datasource:
    url: "jdbc:mysql://localhost:3306/appointment_bookingdb?createDatabaseIfNotExist=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: "#Abhishek123" //replace with your key
  #    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest


  mail:
    host: smtp.gmail.com
    port: 587
    username: abcd@gmail.com //replace with your 
    password: abcd abcd abcd abcd //replace with your
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      access: read_only
    health:
      probes:
        enabled: true

  info:
    env:
      enabled: true

endpoints:
  shutdown:
    enabled: true

razorpay:
  api:
    key: rzp_test_TR5QZYLmJabcd //replace with your key
    secret: T6aH37uqIwJK1KyrHEwabcd //replace with your key

stripe:
  api:
    key: sk_test_xxxxxxxxxxxxxxxxxxxbeNk46ajzwrO22PT5gh3gixFlZQiKzAwboLVnfguvUuqSk4iWPmxxxxxxxxx //replace with your key


eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "Payment Service"
    description: "Payment Service API For Business Booking System"
    version: "1.0.0"
